services:
  db:
    image: pgvector/pgvector:pg16
    container_name: veripack-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: veripack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - veripack-postgres-data:/var/lib/postgresql/data

volumes:
  veripack-postgres-data:
